"""init

Revision ID: 82411607708d
Revises: 
Create Date: 2024-02-22 09:56:27.449857

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82411607708d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comp_game_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vert_index', sa.String(), nullable=True),
    sa.Column('horiz_index', sa.String(), nullable=True),
    sa.Column('ship', sa.String(), nullable=True),
    sa.Column('id_ship', sa.String(), nullable=True),
    sa.Column('create_date', sa.String(), nullable=True),
    sa.Column('field_class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('player_game_field',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vert_index', sa.String(), nullable=True),
    sa.Column('horiz_index', sa.String(), nullable=True),
    sa.Column('ship', sa.String(), nullable=True),
    sa.Column('id_ship', sa.String(), nullable=True),
    sa.Column('create_date', sa.String(), nullable=True),
    sa.Column('field_class', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('player_game_field')
    op.drop_table('comp_game_field')
    # ### end Alembic commands ###
